In [1]:
import numpy as np
import tensorflow as tf

In [2]:
def print_tensor_details(tensor):
    print(f"tensor = {tensor}")
    print(f"size or tensor = {len(tensor)}")
    print(f"no of dimensions in tensor = {tensor.ndim}")
    print(f"shape of tensor = {tensor.shape}")
    print(f"data type of every element = {tensor.dtype}")

In [4]:
vector=tf.zeros(5)
print_tensor_details(vector)

tensor = [0. 0. 0. 0. 0.]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'float32'>


In [5]:
matrix = tf.zeros([2, 3])
print_tensor_details(matrix)

tensor = [[0. 0. 0.]
 [0. 0. 0.]]
size or tensor = 2
no of dimensions in tensor = 2
shape of tensor = (2, 3)
data type of every element = <dtype: 'float32'>


In [6]:
tensor_3d = tf.zeros([2, 3, 4])
print_tensor_details(tensor_3d)

tensor = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
size or tensor = 2
no of dimensions in tensor = 3
shape of tensor = (2, 3, 4)
data type of every element = <dtype: 'float32'>


In [7]:
tensor_1d =tf.ones(5)
print_tensor_details(tensor_1d)

tensor = [1. 1. 1. 1. 1.]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'float32'>


In [9]:
tensor_2d =tf.ones([2,3])
print_tensor_details(tensor_2d)

tensor = [[1. 1. 1.]
 [1. 1. 1.]]
size or tensor = 2
no of dimensions in tensor = 2
shape of tensor = (2, 3)
data type of every element = <dtype: 'float32'>


In [10]:
tensor_1d = tf.constant([10, 20, 30, 40, 50], dtype=tf.float16)
print_tensor_details(tensor_1d)

tensor = [10. 20. 30. 40. 50.]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'float16'>


In [11]:
tensor_1d = tf.zeros(5, dtype=tf.int16)
print_tensor_details(tensor_1d)

tensor = [0 0 0 0 0]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'int16'>


In [12]:
tensor_1d = tf.ones(5, dtype=tf.int16)
print_tensor_details(tensor_1d)

tensor = [1 1 1 1 1]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'int16'>


In [13]:
tensor_1d=tf.fill(5,7)
print_tensor_details(tensor_1d)

tensor = [7 7 7 7 7]
size or tensor = 5
no of dimensions in tensor = 1
shape of tensor = (5,)
data type of every element = <dtype: 'int32'>


In [14]:
tensor_2d=tf.fill((3,3),88)
print_tensor_details(tensor_2d)


tensor = [[88 88 88]
 [88 88 88]
 [88 88 88]]
size or tensor = 3
no of dimensions in tensor = 2
shape of tensor = (3, 3)
data type of every element = <dtype: 'int32'>


In [16]:
tensor=tf.constant([[10,20],[30,40],[50,60]])


In [17]:
tensor_zeros=tf.zeros_like(tensor)
print_tensor_details(tensor_zeros)

tensor = [[0 0]
 [0 0]
 [0 0]]
size or tensor = 3
no of dimensions in tensor = 2
shape of tensor = (3, 2)
data type of every element = <dtype: 'int32'>


In [18]:
tensor_ones =tf.ones_like(tensor)
print_tensor_details(tensor_ones)

tensor = [[1 1]
 [1 1]
 [1 1]]
size or tensor = 3
no of dimensions in tensor = 2
shape of tensor = (3, 2)
data type of every element = <dtype: 'int32'>


In [19]:
tensor_sixes = tf.fill(tensor.shape,6)
print_tensor_details(tensor_sixes)

tensor = [[6 6]
 [6 6]
 [6 6]]
size or tensor = 3
no of dimensions in tensor = 2
shape of tensor = (3, 2)
data type of every element = <dtype: 'int32'>
